## 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [4]:
import pandas as pd

In [5]:
cavideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\CAvideos.csv")
frvideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\FRvideos.csv")
devideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\DEvideos.csv")
gbvideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\GBvideos.csv")
invideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\INvideos.csv")
jpvideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\JPvideos.csv", encoding_errors = "replace")
krvideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\KRvideos.csv", encoding_errors = "replace")
mxvideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\MXvideos.csv", encoding_errors = "replace")
ruvideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\RUvideos.csv", encoding_errors = "replace")
usvideos = pd.read_csv(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\csv\USvideos.csv")

In [6]:
cavideos["country"] = "CA"
frvideos["country"] = "FR"
devideos["country"] = "DE"
gbvideos["country"] = "GB"
invideos["country"] = "IN"
jpvideos["country"] = "JP"
krvideos["country"] = "KR"
mxvideos["country"] = "MX"
ruvideos["country"] = "RU"
usvideos["country"] = "US"

In [7]:
tot = pd.concat([cavideos, frvideos, devideos, gbvideos, invideos, jpvideos, krvideos, mxvideos, ruvideos, usvideos])
tot

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

We we inserted an index because we need it to delete rows in exercise 4.

In [8]:
indici=[]
for i in range(0,len(tot)):
    indici.append(i)
tot["index"] = indici

In [9]:
tot=tot.set_index('index')

In [10]:
tot.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description', 'country'],
      dtype='object')

## 2. Extract all videos that have no tag.

In [11]:
tot[tot["tags"] == "[none]"]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
index,,,,,,,,,,,,,,,,,
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375815,VGykknw9eCM,18.14.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],3577614,12318,1345,1414,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US
375819,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,US
375865,gS1DbvHHVH0,18.14.06,Going in to brain surgery,Simone Giertz,28,2018-05-30T14:22:13.000Z,[none],1635301,120791,1098,20711,https://i.ytimg.com/vi/gS1DbvHHVH0/default.jpg,False,False,False,We’ll post an update on Instagram and Twitter ...,US
375873,E4c7EE8_IX0,18.14.06,Weezer - Africa,weezer,10,2018-05-29T12:00:11.000Z,[none],4682557,115240,5069,9170,https://i.ytimg.com/vi/E4c7EE8_IX0/default.jpg,False,False,False,Stream + download the song: http://fanlink.to/...,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US

We will have all video without tag: tag == [none]

## 3. For each channel, determine the total number of views

In [12]:
tot.groupby("channel_title")["views"].sum().reset_index()

                channel_title    views
0                  ! 세상에 무슨일이  3942977
1               !!8時だよ面白ネタ大集合    50207
2              !BTS・TWICE まとめ     7310
3      !Los amorosos Virales¡     6069
4                     !t Live   240038
...                       ...      ...
37819              ５分でできる DIY   272607
37820                  ＢＡＳＨｔｖ   116292
37821           Ｋのフィッシングちゃんねる    37165
37822                 ＷＡＪＯＩＫＡ   424129
37823                💜Sandrea   347155

[37824 rows x 2 columns]

Since the same country appears multiple times, we will have an incorrect total of views per channel. By viewing the dataset, we notice that the views are cumulative, so we will only have to take the last time they appear based on the trending date.

In [13]:
tot[tot['video_id']=='2Vv-BfVoq4g'][['trending_date','title','views','country']]

,trending_date,title,views,country
index,,,,
4,17.14.11,Ed Sheeran - Perfect (Official Music Video),33523622,CA
282,17.15.11,Ed Sheeran - Perfect (Official Music Video),39082222,CA
41055,17.14.11,Ed Sheeran - Perfect (Official Music Video),33523622,FR
81636,17.14.11,Ed Sheeran - Perfect (Official Music Video),33523622,DE
122451,17.14.11,Ed Sheeran - Perfect (Official Music Video),33523622,GB
122673,17.15.11,Ed Sheeran - Perfect (Official Music Video),39082222,GB
122885,17.16.11,Ed Sheeran - Perfect (Official Music Video),43449654,GB
123130,17.17.11,Ed Sheeran - Perfect (Official Music Video),48461709,GB
123340,17.18.11,Ed Sheeran - Perfect (Official Music Video),56525948,GB
123548,17.19.11,Ed Sheeran - Perfect (Official Music Video),65651096,GB
123758,17.20.11,Ed Sheeran - Perfect (Official Music Video),74009550,GB
123971,17.21.11,Ed Sheeran - Perfect (Official Music Video),82143174,GB
124178,17.22.11,Ed Sheeran - Perfect (Official Music Video),91081966,GB
124412,17.23.11,Ed Sheeran - Perfect (Official Music Video),100488035,GB
124622,17.24.11,Ed Sheeran - Perfect (Official Music Video),109625533,GB
124832,17.25.11,Ed Sheeran - Perfect (Official Music Video),119263821,GB
125036,17.26.11,Ed Sheeran - Perfect (Official Music Video),129460449,GB
125239,17.27.11,Ed Sheeran - Perfect (Official Music Video),138578860,GB
161451,17.14.11,Ed Sheeran - Perfect (Official Music Video),33523622,IN
161738,17.15.11,Ed Sheeran - Perfect (Official Music Video),39082222,IN
335063,17.14.11,Ed Sheeran - Perfect (Official Music Video),33523622,US
335329,17.15.11,Ed Sheeran - Perfect (Official Music Video),39082222,US
335567,17.16.11,Ed Sheeran - Perfect (Official Music Video),43449654,US

In [14]:
tot_3=tot.sort_values(['video_id','trending_date'])

So we sort the dataset first by video_id so that we have the same videos next to each other, and then by trending_date so that we can see the date with the most views as the latest. Now we need to eliminate all the videos with unwanted views.

In [15]:
tot_3 = tot_3.drop_duplicates(subset=["video_id", "channel_title"], keep = "last")

Now that we've eliminated the videos with the same video_id and channel_title and kept the last one, we can sum the views per channel of this last dataset.

In [16]:
view_per_canale = tot_3.groupby("channel_title")["views"].sum()
view_per_canale.reset_index()

                channel_title    views
0                  ! 세상에 무슨일이  1052789
1               !!8時だよ面白ネタ大集合    50207
2              !BTS・TWICE まとめ     7310
3      !Los amorosos Virales¡     6069
4                     !t Live   194690
...                       ...      ...
37819              ５分でできる DIY   183245
37820                  ＢＡＳＨｔｖ   116292
37821           Ｋのフィッシングちゃんねる    37165
37822                 ＷＡＪＯＩＫＡ   424129
37823                💜Sandrea   188204

[37824 rows x 2 columns]

## 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [17]:
righe_iniziali = tot.shape[0]

In [18]:
excluded = tot[(tot["comments_disabled"] == True) & (tot["ratings_disabled"] == True) | tot["video_error_or_removed"] == True]
excluded.shape

(2620, 17)

In [19]:
tot = tot.drop(excluded.index)
tot.shape

(373322, 17)

In [20]:
righe_iniziali == tot.shape[0] + excluded.shape[0]

True

To check that it is correct we check that the number of rows of the initial tot is equal to the final one, excluding the excluded ones

## 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

Fixed the issue when the number of dislikes is 0

In [21]:
tot["like_ratio"] = tot["likes"].div(tot["dislikes"].replace(0, pd.NA))

In [22]:
tot["like_ratio"]

index
0          18.135076
1          75.707346
2            27.3525
3          66.485168
4          77.513044
             ...
375937     27.552347
375938    157.089005
375939     46.577519
375940     67.799368
375941      1.676616
Name: like_ratio, Length: 373322, dtype: object

## 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

Convert into datetime

In [23]:
tot['publish_time'] = pd.to_datetime(tot['publish_time'])

We extract only hours and minutes

In [24]:
tot['time_only'] = tot['publish_time'].dt.time

We create a column for 10-minute intervals and then we go to create the intervals,
extracting the minutes from midnight (from 0 to 1439) we divide by 10 minutes creating the intervals

In [25]:
tot['minutes_from_midnight'] = tot['publish_time'].dt.hour * 60 + tot['publish_time'].dt.minute
tot['interval_10min'] = (tot['minutes_from_midnight'] // 10) * 10

def format_interval(minutes):
    start_hour = minutes // 60
    start_min = minutes % 60
    end_minutes = minutes + 10
    end_hour = (end_minutes // 60) % 24
    end_min = end_minutes % 60
    return f"{start_hour:02d}:{start_min:02d}-{end_hour:02d}:{end_min:02d}"
tot['interval_label'] = tot['interval_10min'].apply(format_interval)

In [26]:
tot.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description', 'country', 'like_ratio',
       'time_only', 'minutes_from_midnight', 'interval_10min',
       'interval_label'],
      dtype='object')

## 7. For each interval, determine the number of videos, average number of likes and of dislikes.

We calculate for each interval the number of videos, the average of likes and dislikes, 
then we add the labels and reorder the columns.

In [27]:
# De-duplication: for each video we keep only the last one
tot_7 = tot.sort_values(['video_id', 'trending_date'])
tot_7 = tot_7.drop_duplicates(subset=['video_id', 'publish_time', 'channel_title'], keep='last')

# Aggregation
interval_stats = tot_7.groupby('interval_10min').agg(
    num_videos=('video_id', 'count'),
    avg_likes=('likes', 'mean'),
    avg_dislikes=('dislikes', 'mean')
)

interval_stats['interval'] = interval_stats.index.map(format_interval)
interval_stats = interval_stats[['interval', 'num_videos', 'avg_likes', 'avg_dislikes']]
interval_stats

                   interval  num_videos     avg_likes  avg_dislikes
interval_10min
0               00:00-00:10        1391  11022.872035    937.304098
10              00:10-00:20         752   7148.655585    415.567819
20              00:20-00:30         658   7765.366261    638.770517
30              00:30-00:40         845   7189.547929    316.145562
40              00:40-00:50         641   8119.082683    458.180967
...                     ...         ...           ...           ...
1390            23:10-23:20         808   7461.243812    465.487624
1400            23:20-23:30         723   9726.387275    608.475795
1410            23:30-23:40         909   6541.635864    406.011001
1420            23:40-23:50         743   9306.825034   1086.104980
1430            23:50-00:00         694   5505.651297    379.634006

[144 rows x 4 columns]

## 8. For each tag, determine the number of videos. Notice that tags contains a string with several tags.

In [28]:
tot['tags']=tot['tags'].str.replace('"','')
tot['tags']=tot['tags'].str.replace('#','')
tot['tags']=tot['tags'].str.replace('/','|')
tot['tags']=tot['tags'].str.replace('#','')

In [29]:
tot['tags'] = tot['tags'].str.split('|')
exploded = tot.explode('tags')
exploded = exploded[
    (exploded["tags"].notna()) &
    (exploded["tags"] != "") &
    (exploded["tags"] != "[none]")
]
tag_counts = exploded['tags'].value_counts().reset_index(name="numerodivideo")
tag_counts

                                                     tags  numerodivideo
0                                                   funny          15039
1                                                  comedy          12351
2                                                    2018          11912
3                                                    news           6488
4                                                   music           5939
...                                                   ...            ...
847159                          silikon verarbeiten video              1
847160                                        Silitub.com              1
847161  Bandla Ganesh Vs Jeevan Reddy over Pawan Kalya...              1
847162                                            Silitub              1
847163                                      fotografiando              1

[847164 rows x 2 columns]

## 9. Find the tags with the largest number of videos

In [30]:
tag_counts.iloc[0]

tags             funny
numerodivideo    15039
Name: 0, dtype: object

## 10. For each (tag, country) pair, compute average ratio likes/dislikes

We use the exploded dataset because it already has all the tags separated from each other

In [31]:
result = exploded.groupby(["tags", "country"])["like_ratio"].mean().reset_index()
result

                                                      tags country like_ratio
0         ''A por la FORTALEZA'' Capitulo 88 - Segunda ...      MX   2.631019
1               ''Es mucho lo que el país le debe al PRI''      MX   74.02381
2                      'Gandarrappido: The Revenger Squad       CA  20.697017
3                                  (2018) ¿Cual Prefieres?      MX      56.05
4                                   (BLAYA - FAZ GOSTOSO)       FR  25.577882
...                                                    ...     ...        ...
1096580                                                  😥      DE  26.384615
1096581                    😭 résistancelamaindesqueezie ❤️      FR  10.219048
1096582    😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية      FR   6.223873
1096583                                🚀 smartpixel.com.ua      RU   0.714286
1096584                       🤝 ZARBEX zahlt Schutzgeld!!!      DE  13.989691

[1096585 rows x 3 columns]

## 11. For each (trending_date, country) pair, the video with the largest number of views

In [32]:
most_views = tot.groupby(["trending_date", "country"])["views"].idxmax().reset_index(name="max_index")
most_views["video_id"] = tot.loc[most_views["max_index"], "video_id"].values
most_views["views"] = tot.loc[most_views["max_index"], "views"].values
most_views[["trending_date", "country", "video_id", "views"]]

     trending_date country     video_id      views
0         17.01.12      CA  6ZfuNTqbHE8   56367282
1         17.01.12      DE  6ZfuNTqbHE8   56367282
2         17.01.12      FR  3VbHg5fqBYw    7281189
3         17.01.12      GB  TyHvyGVs42U  143408235
4         17.01.12      IN  6ZfuNTqbHE8   56367282
...            ...     ...          ...        ...
1962      18.31.05      JP  aJOTlE1K90k    3057987
1963      18.31.05      KR  ntWSnDV0MYs    4150448
1964      18.31.05      MX  xTlNMmZKwpA   20723565
1965      18.31.05      RU  1nX0kF2UwDc    3125598
1966      18.31.05      US  VYOjWnS4cMY  217750076

[1967 rows x 4 columns]

## 12. Divide trending_date into three columns: year, month, day

In [33]:
tot["trending_date_dt"] = pd.to_datetime(
    tot["trending_date"],
    format="%y.%d.%m"
)
tot["year"] = tot["trending_date_dt"].dt.year
tot["month"] = tot["trending_date_dt"].dt.month
tot["day"] = tot["trending_date_dt"].dt.day

tot

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,country,like_ratio,time_only,minutes_from_midnight,interval_10min,interval_label,trending_date_dt,year,month,day
index,,,,,,,,,,,,,,,,,,,,,
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"[Eminem, Walk, On, Water, Aftermath, Shady, In...",17158579,787425,43420,...,CA,18.135076,17:00:03,1020,1020,17:00-17:10,2017-11-14,2017,11,14
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"[plush, bad unboxing, unboxing, fan mail, idub...",1014651,127794,1688,...,CA,75.707346,17:00:00,1020,1020,17:00-17:10,2017-11-14,2017,11,14
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"[racist superman, rudy, mancuso, king, bach, r...",3191434,146035,5339,...,CA,27.3525,19:05:24,1145,1140,19:00-19:10,2017-11-14,2017,11,14
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"[ryan, higa, higatv, nigahiga, i dare you, idy...",2095828,132239,1989,...,CA,66.485168,18:01:41,1081,1080,18:00-18:10,2017-11-14,2017,11,14
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"[edsheeran, ed sheeran, acoustic, live, cover,...",33523622,1634130,21082,...,CA,77.513044,11:04:14,664,660,11:00-11:10,2017-11-14,2017,11,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"[aarons animals, aarons, animals, cat, cats, k...",1685609,38160,1385,...,US,27.552347,13:00:04,780,780,13:00-13:10,2018-06-14,2018,6,14
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[[none]],1064798,60008,382,...,US,157.089005,01:00:06,60,60,01:00-01:10,2018-06-14,2018,6,14
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,[I gave safiya nygaard a perfect hair makeover...,1066451,48068,1032,...,US,46.577519,17:34:22,1054,1050,17:30-17:40,2018-06-14,2018,6,14
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"[Black Panther, HISHE, Marvel, Infinity War, H...",5660813,192957,2846,...,US,67.799368,17:00:04,1020,1020,17:00-17:10,2018-06-14,2018,6,14
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"[call of duty, cod, activision, Black Ops 4]",10306119,357079,212976,...,US,1.676616,17:09:38,1029,1020,17:00-17:10,2018-06-14,2018,6,14

## 13. For each (month, country) pair, the video with the largest number of views

In [34]:
most_views2 = tot.groupby(["month", "country"])["views"].idxmax().reset_index(name="max_index")
most_views2["video_id"] = tot.loc[most_views2["max_index"], "video_id"].values
most_views2["views"] = tot.loc[most_views2["max_index"], "views"].values
most_views2[["month", "country", "video_id", "views"]]

    month country     video_id      views
0       1      CA  LsoLEjrDogU   43067983
1       1      DE  LsoLEjrDogU   37728802
2       1      FR  LsoLEjrDogU   37728802
3       1      GB  LsoLEjrDogU   90598955
4       1      IN  dfnCAmr569k   42019590
..    ...     ...          ...        ...
72     12      IN  FlsCjmMhFmw  125432237
73     12      KR  FlsCjmMhFmw  113876217
74     12      MX  FlsCjmMhFmw  100912384
75     12      RU  FlsCjmMhFmw   52611730
76     12      US  FlsCjmMhFmw  149376127

[77 rows x 4 columns]

## 14. Read all json files with the video categories

In [35]:
CA_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\CA_category_id.json")
DE_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\DE_category_id.json")
FR_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\FR_category_id.json")
GB_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\GB_category_id.json")
IN_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\IN_category_id.json")
JP_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\JP_category_id.json")
KR_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\KR_category_id.json")
MX_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\MX_category_id.json")
RU_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\RU_category_id.json")
US_category_id = pd.read_json(r"C:\Users\bebab\Desktop\Università\Progetti 1 semestre\Foundation of computer science\Progetto\trendingYT\US_category_id.json")

CA_category_id = pd.json_normalize(CA_category_id["items"])
DE_category_id = pd.json_normalize(DE_category_id["items"])
FR_category_id = pd.json_normalize(FR_category_id["items"])
GB_category_id = pd.json_normalize(GB_category_id["items"])
IN_category_id = pd.json_normalize(IN_category_id["items"])
JP_category_id = pd.json_normalize(JP_category_id["items"])
KR_category_id = pd.json_normalize(KR_category_id["items"])
MX_category_id = pd.json_normalize(MX_category_id["items"])
RU_category_id = pd.json_normalize(RU_category_id["items"])
US_category_id = pd.json_normalize(US_category_id["items"])

We add the country column to distinguish the countries

In [36]:
CA_category_id["country"] = "CA"
DE_category_id["country"] = "DE"
FR_category_id["country"] = "FR"
GB_category_id["country"] = "GB"
IN_category_id["country"] = "IN"
JP_category_id["country"] = "JP"
KR_category_id["country"] = "KR"
MX_category_id["country"] = "MX"
RU_category_id["country"] = "RU"
US_category_id["country"] = "US"

In [37]:
totjson = pd.concat([CA_category_id, DE_category_id,FR_category_id,GB_category_id,IN_category_id,JP_category_id,KR_category_id,MX_category_id,RU_category_id,US_category_id])

In [38]:
totjson

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,country
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,CA
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,CA
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,CA
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,CA
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,CA
...,...,...,...,...,...,...,...
27,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,US
28,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,US
29,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,US
30,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,US
31,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,US

## 15. For each country, determine how many videos have a category that is not assignable.

In [39]:
not_assignable = totjson[totjson["snippet.assignable"] == False].groupby(["country", "snippet.assignable"]).size().reset_index(name = "COUNT")
not_assignable

  country  snippet.assignable  COUNT
0      CA               False     17
1      DE               False     17
2      FR               False     17
3      GB               False     17
4      IN               False     17
5      JP               False     17
6      KR               False     17
7      MX               False     17
8      RU               False     17
9      US               False     17